[package]
name = "serde_json_macro"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
cairo-lang-macro = "0.1.1"
cairo-lang-parser = "2.10.1"
cairo-lang-syntax = "2.10.1"
indoc = "2"

[workspace]
